### ISSUE TITLE
Agacta 5. derinlik

### ISSUE THREAD

**Issue by ergenekonyigit** [irfansener/soy-agaci#2]
Oncelikle eline saglik, kodunu refactor ettigini dusunerek pr acmiyorum ama issue olarak belirtmek istedim. Su an calisan halde agac 4. derinlige kadar iniyor. (Ornegin: Annesinin_Annesinin_Annesinin_Annesi) 
Ben kendi soyagacima bakmak istedigimde tamamini goremiyorum cunku bende 5. derinlige kadar gitmesi gerekiyor.  (Ornegin: Annesinin_Annesinin_Annesinin_Annesinin_Annesi) 
Refactor ederken bunu da goz onunde bulundurmak isteyebilirsin. 🙂

**Comment by irfansener** [comment]
Sorunun farkındayım. Aslında 3'er satır daha kod ekleyip bu sorunu çözebilirim. Sanırım 5'ten daha derin ağaçlar oluşturmuyordur. Fakat mantıklı bir algoritma kurup el ile yazdığım kodları okunabilir hale getirmeye çalışıyorum. En kısa sürede giderilmiş olur. Geri bildirimin için teşekkürler.
