### ISSUE TITLE
Ufak bir düzeltme

### ISSUE THREAD

**Issue by abdurrahmanekr** [irfansener/soy-agaci#4]
Merhaba repository gerçekten güzel olmuş ellerine sağlık :). Bence şu satırda direkt bu repository'nin linkini verebilirsin.
https://github.com/irfansener/soy-agaci/blob/7b574fe4a54915cca93f5aba8d882cd2df439bd6/src/components/Home.vue#L19

**Comment by irfansener** [comment]
Teşekkürler.
