### ISSUE TITLE
kardeş site bozuk sanırım.

### ISSUE THREAD

**Issue by emrebaba30** [irfansener/soy-agaci#5]
html ındırıyorum o kısımdan secıyorum ama sonra ekran boş kalıyor o ip ile gırılmıyor artık hep ekran bos kalıyor

**Comment by irfansener** [comment]
Ip ile ilgili değil, tarayıcı önbelleği ile alakalı son 24 saatlik önbellek ve site verilerini temizlerseniz, sorununuz düzelecektir.
